---
title: "The Right to Vote - Draft Notes"
author: "Prof. Jonathan Cervas"
date: "Updated: `r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    keep_tex: no
  powerpoint_presentation:
  md_document:
    variant: gfm
  html_document:
    theme: yeti
    highlight: textmate
  beamer_presentation:
    keep_tex: no
    theme: "Pittsburgh"
    colortheme: "beaver"
    fonttheme: "structurebold"
classoption: aspectratio=169
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

## rmarkdown::render('/Users/cervas/Library/CloudStorage/GoogleDrive-jcervas@uci.edu/My Drive/GitHub/teaching/classes/class-cmu-84-352/lecture-slides/the-right-to-vote-lecure-slides/The-Right-to-Vote-Part-II.Rmd', output_format = 'all')
```

## Reforms against suffrage
>- Proposals for reducing the electorate found their way onto the public agenda in the 1870s and remained there for decades
>- Proposals included:
>	+ less frequent elections
>	+ at-large rather than district voting
>	+ increased public accountability for office holders
>	+ state control over key arenas of municipal administration
>	+ remove public offices from the electoral sphere and make them appointive
>	    + It was "absurd" to involve the electorate in "the selection of judges and sheriffs, and district attorneys, of state treasurers and attorney-generals, of school commissioners and civil engineers."
>	    + **In other words, democracy could be salvaged by circumscribing its domain**

## Reforms to strength democracy
>- Other critics were more optimistic about the possibilities of changing the size and shape of the electorate
>- Some advocated reinstituting property and tax qualifications or imposing literacy tests on prospective voters
>- More subtle approaches also were proposed, including 
>	+ longer residence periods
>	+ stricter naturalization laws
>	+ waiting periods before new citizens could vote
>	+ complex ballot laws
>	+ elaborate systems of voter registration

## Purifying the Electorate

## Revising the rules
>- The laws governing elections in most states were revised often between the Civil War and World War I
>- States held constitutional conventions that defined or redefined the shape of the electorate and outlined of the electoral process
>- State legislatures drew up increasingly detailed statutes that spelled out electoral procedures of all types
>	+ timing of elections
>	+ location of polling places
>	+ hours that polls would be open
>	+ configuration of ballots
>	+ counting of votes
>- Many of these laws were straightforwardly administrative, while other laws were more controversial, inspired by partisan interests, enacted to influence the outcome of elections

## Institutional reforms
>- The apportionment of state legislative as well as congressional seats was a key issue
>    + generated recurrent conflicts, particularly between urban and rural areas
>- Linked to apportionment was the location of district boundaries in states and within cities
>	+ gerrymandering was a routine form of political combat
>	+ it was practiced by both major parties against one another and against any upstart political organizations
>- Technical rules governing the presence of parties and candidates on the ballot also were subjects of contention
>	+ they could encourage, or discourage, third parties and fusion slates

## The electorate
>- The most critical laws remained those that determined the size and contours of the electorate
>- These were of two types.
>	+ First and most important were those that set out the fundamental qualifications that a man (or woman) had to meet in order to become an eligible voter
>	+ The second, of increasing significance, established the procedures that a potential voter had to follow in order to participate in elections
>- **The Constitution and federal courts had little to say about suffrage (outside of race), and therefore the rules remained under _state control_**

## Money and the Vote

## Economic qualifications
>- Economic requirements for voting were not a dead issue after 1850
>- Economic qualifications continued to offer opponents of universal suffrage a direct and potentially efficient means of winnowing out undesirable voters
>- The tax requirement had served two purposes:
>	+ as an obstacle to poor people’s voting 
>	+ as a drain on the treasuries of both political parties
>		+ for example, by the late 1880s, the Massachusetts Democratic Party –with more working-class supporters and thus greater financial exposure– reportedly was spending $50,000 in each election to pay the poll taxes of its supporters
>- In the North, a poll tax was used by the Republicans to disenfranchise the poor, often immigrants, who more often than not supported Democrats
>	+ combined with apportionment schemes and bans on foreign-born voting, Republican elites in the countryside kept power from those in cities

## Court on economic constraints
>- The U.S. Supreme Court made clear that it too did not see anything unconstitutional about taxpaying or property requirements  (_Myers v. Anderson_, 1915)
>	+ The Court found the law to be racially discriminatory in violation of the _Fifteenth Amendment_ 
>	+ however, it noted that economic discrimination in the form of a property requirement was presumed to be "free from constitutional objection"
>		+ the _Twentyfourth Amendment_, ratified in 1964, abolishes any poll tax

## Class motivation
>- Overtly class-based economic restrictions were accompanied by legal changes expressly designed to reduce the number of "undesirable" immigrants who could vote
>- Beginning in the 1890s, the nation witnessed the growth of a significant movement to **restrict immigration altogether**
>	+ widespread middle-class anxiety about the impact of the foreign-born on politics, particularly urban politics
>- The effort to keep immigrants from the polls was distinct from the movement for outright restriction
>	+ it bore fruit long before Congress passed the pathbreaking restriction and quota acts of 1921 and 1924
>- As the ratio of immigrant workers to settlers soared and the need to encourage settlement diminished, granting the franchise to non-citizens seemed increasingly undesirable and risky.

## Alien suffrage
>- Most states rejected alien suffrage proposals in the late nineteenth century
>	+ beginning with Idaho territory in 1874, states that had permitted non-citizens to vote began to repeal their declarant alien provisions
>	+ picked up steam in the wake of the depression of the 1890s and the assassination of President McKinley by an immigrant in 1901
>	+ it accelerated again during and after World War I, when concerns about the loyalty of the foreign–born contributed to a rare instance of wartime contraction of the franchise.
>- The last state to permit non-citizens to vote was Arkansas, which abolished the practice in 1926
Alien suffrage
>- Numerous states placed new obstacles in the path of immigrant voters
>	+ Most were supported by some Republicans, opposed by Democrats, and justified on the grounds that they would reduce fraud
>	+ Required naturalized citizens to present their naturalization papers to election officials before registering or voting
>	+ Although not unreasonable on its face, this requirement, as lawmakers knew, was a significant procedural hurdle for many immigrants, who might easily have lost their papers or been unaware of the requirement
>	+ when coupled with provisions that permitted anyone present at the polls to challenge the credentials of immigrant voters, these laws placed substantial discretionary power in the hands of local officials

## Reducing immigrant voting
>- The concerns that prompted such efforts to keep immigrants from the polls also contributed to the tightening of federal immigration and naturalization laws between 1880 and the 1920s
>- Beginning in 1882, Congress began to narrow the channels through which the flow of European immigrants passed
>- Between 1906 and 1910, Congress codified the naturalization laws
>	+ prohibited many "undesirable" foreign-born residents from becoming citizens
>	+ set a time limit on the validity of declarations of intent
>	+ required candidates for naturalization to write their own names and present ample proof (including witnesses) of their eligibility and continuous residence in the United States for five years

## Purpose of the laws
>- These laws were unabashedly aimed at making it more difficult for men and women to become citizens, and by all accounts they succeeded, reducing the proportion of immigrants who could vote
>- The most controversial reform of the immigration laws was the imposition of a literacy or education test for admission to the United States
>	+ support of a unique coalition of northern professionals, many Republicans, southern Democrats, anti-Catholics, anti-Semites, and the American Federation of Labor
>		+ the bill’s target was the “new” immigrant population, eastern and southern Europeans who had high rates of illiteracy (more than 20 percent in 1914) and who generally were regarded as less desirable than their English, German, Scandinavian, and even Irish predecessors

## Asian immigrants
>- Intense as apprehensions about poor European immigrants may have been, they paled in comparison to American attitudes toward the Chinese and other east Asians
>- By the final quarter of the nineteenth century, most Americans –and especially those on the West Coast– wanted not only to keep the Chinese from voting but to halt Chinese immigration and even deport those who were already here
>- Feared because of their willingness to work for low wages and despised for racial and cultural reasons, the Chinese had never been a significant political presence because they had almost always been treated as nonwhite and therefore ineligible for citizenship
>- California Constitutional Convention of 1878–1879: "no native of China" (the wording was aimed at circumventing the _Fifteenth Amendment_’s ban on racial barriers) "shall ever exercise the privileges of an elector in this State"
>	+ The suffrage provision of the 1879 constitution remained in force until 1926

## Educated Voters

_A knowledge of the language of our laws and the faculty of inform- ing oneself without aid of their provisions, would in itself constitute a test, if rigorously enforced, incompatible with the existence of a proletariat._

-- Charles Francis Adams, Jr. “Protection of the Ballot” (1869)

## Literacy tests
>- Perhaps the most popular method of constricting the electorate was the literacy or education test
>	+ Massachusetts and Connecticut adopted tests in the 1850s
>- Requiring voters to be literate, particularly in English, had a number of apparent virtues
>	+ it would reduce the "ignorance" of the electorate and weed out sizable numbers of poor immigrant voters (outside of the South, the native-born population was almost entirely literate)
>	+ it was more palatable than taxpaying restrictions or waiting periods for the foreign-born
>	+ literacy tests did not overtly discriminate against particular classes or ethnic groups, and illiteracy itself was a remediable shortcoming

## Justifications for literacy tests
1. illiterate men lacked the intelligence or knowledge necessary to be wise or even adequate voters
2. (aimed at new immigrants) English-language literacy was essential for the foreign-born to become properly acquainted with American values and institutions
3. tying voting to literacy would encourage assimilation and education, which would benefit American society as well as immigrants themselves

## Australian ballot
>- An indirect and limited means of promoting a literate electorate was the adoption of the secret or Australian ballot.
>- For much of the nineteenth century, voters had obtained their ballots from political parties
>	+ since the ballots generally contained only the names of an individual party’s candidates, literacy was not required
>	+ all that a man had to do was drop a ballot in a box
>	+ since ballots tended to be of different sizes, shapes, and colors, a man’s vote was hardly a secret
>		+ to election officials, party bosses, employers, or anyone else watching the polls
>- Australian Ballot first appeared in Australia in 1856 and then was implemented in England in 1872

## Australian ballot
>- The Australian ballot was an effort to allow people to freely support whoever they wanted and from corruption and intimidation
>	+ It was a standard ballot, usually printed by the city or state, containing the names of all candidates for office
>- The voter (often in private) placed a mark by the names of the candidates or parties for whom he wished to vote
>	+ The democratic virtues of secret voting were widely apparent
>- The Australian ballot was an obstacle to participation by many illiterate foreign-born voters in the North, as well as uneducated Black voters in the South
>	+ In some states, this problem was remedied by expressly permitting illiterate voters to be assisted or by attaching party emblems to the names of candidates

## Increasing literacy tests in the North
>- Opposition to literacy test was strong (outside of the South)
>	+ Northern Democrats, who counted the urban poor among their constituents, generally voted against education requirements
>	+ So too did politically organized ethnic groups, regardless of their party affiliation, which helps to explain why no English-language literacy tests were imposed in the Midwest
>		+ the German and Scandinavian communities of the Midwest, though often allied with the Republicans, vehemently opposed education requirements
>- Even so, by the mid-1920s, thirteen states in the North and West were disfranchising illiterate citizens who met all other eligibility requirements
>- In all of these states, the Republican Party was strong
>	+ several had large immigrant populations that played important roles in party competition
>	+ a handful of others were predominantly rural states with small but visible clusters of poor foreign-born voters
>	+ several had significant Native-American populations

## Literacy test effects
>- The potential impact of these literacy laws–all of which were sanctioned by the courts–was enormous.
>- According to the census (which relied on self-reporting), there were nearly five million illiterate men and women in the nation in 1920
>	+ this was roughly 8 percent of the voting-age population
>- Other sources suggest that in fact the figure was much higher
>	+ Twenty-five percent of men who took an army literacy test during World War I were judged to be illiterate and another 5 percent semiliterate
>- **A reasonable estimate is that a minimum of several hundred thousand voters –and likely more than a million– were barred by literacy tests outside of the South**

## Migrants and Residents
>- The difficulty of defining or establishing residence was becoming more complex
>	+ in Boston, only 64% of residents who lived there in 1880 still lived there in 1890
>- There was an increasingly accepted legal notion that sheer physical presence in a community for a specified length of time was not sufficient for a person to be considered a resident
>	+ Physical presence thus had to be accompanied by the intention of remaining in a community for what the courts came to describe as "an indefinite period"
>	+ Although the concept was reasonable, intention could be difficult to ascertain or prove
>- Courts found themselves evolving criteria to gauge the intentions of both individuals and groups (such as ministers and railway workers, who were often on the move) as they tried to apply broadly stated laws to extremely varied situations.
>- The insistence on intention tended to make legal residence harder to establish, especially for men whose occupations demanded mobility

## Residency
>- No jurisdiction questioned the legitimacy of statutes or constitutional amendments establishing residence qualifications (even lengthy residence qualifications) for voting
>- The U.S. Supreme Court in _Pope v. Williams_ (1904) affirmed the constitutionality of residency qualifications and state efforts to enforce them
>- While the courts debated the _definition_ of residence, constitutional conventions, and sometimes legislatures, determined the appropriate length of residency requirements
>- In much of the nation, there was a broad consensus that a year’s residence in the state was necessary and sufficient for a man to responsibly exercise the franchise
>	+ in many midwestern states the consensus period was six months

## Education and residency
>- The most difficult case proved to be students at colleges, seminaries, and other institutions of higher learning
>- In many states, there was substantial sentiment in favor of prohibiting students from gaining residence in the communities where they attended college: 
>	+ claiming that students were not truly members of the community, political leaders cited anecdotes of:
>		+ students being paraded to the polls to vote en masse
>		+ of unscrupulous politicians enlisting students to cast their ballots
>		+ of students (who did not pay taxes) voting to impose tax increases on permanent residents
>- There was a notable degree of resistance to such laws grounded in a reluctance to keep respectable, middle-class, native-born men from voting

## Physical presence
>-The notion that legal residence was tied as much to intention as physical presence inexorably led states to consider mechanisms for absentee voting
>	+ for men and women who were temporarily away from home but intended to return
>- The Civil War and the desire to permit soldiers to vote during the war severed the link between voting and physical presence in a community
>- World War I added a new urgency to the issue, since nearly three million men were inducted into the army
>- By 1918, nearly all states had made provisions for men serving in the military to cast their ballots, at least in time of war

## Absentee voting (i.e., mail-in ballots)
>- By the end of World War I, more than twenty states had provided for absentee voting on the part of anyone who could demonstrate a work-related reason (and in a few cases, any reason) for being absent on election day.
>- Concerns about fraud generally were alleviated by tight procedural rules and requirements that absentee ballots be identical to conventional ones
>- A conservative estimate would be that 5–10 percent of the nation’s adult population failed to meet the residency requirements at each election which was high enough to have potentially changed the outcomes of innumerable elections

## Keeping Track of Voters
>- Before the 1870s in most states, there were no official preprepared lists of eligible voters
>- Men who sought to vote were not obliged to take any steps to establish their eligibility prior to election day
>- Between the 1870s and World War I the majority of states adopted formal registration procedures, particularly for their larger cities
>- The rationale for requiring voters to register and have their eligibility certified in advance of elections was straightforward:
>	+ it would help to eliminate fraud and also bring an end to disruptive election-day conflicts at the polls

## Rules for eligibility
>- The devil is in the details:
>	+ How far in advance of elections did a man or woman have to register?
>	+ When would registration offices be open?
>	+ Did one register in the county, the district, the precinct?
>	+ What documents had to be presented and issued?
>	+ How often did one have to register?
>- **All such questions had to be decided, and since the answers inescapably had implications for the composition of the electorate, they were a frequent source of contention**

## Political fights over the rules
>- The two parties also feuded over the hours that the polls would be open
>	+ when the Republicans were able to, they passed laws closing the polls at sunset on the grounds that illegal voting was most likely to occur after dark
>	+ the Democrats protested that "sunset laws" kept workers from voting, and when in power, they extended the hours into the evening
>- Subject to dispute, change, and partisan jockeying:
>	+ the length of the registration period
>	+ its proximity to the date of an election
>	+ the size of registration districts
>	+ the frequency of reregistration
>	+ the necessity of documentary evidence of eligibility
>	+ the location of the burden of proof—all of these

## Early Nineteenth Century Democracy
>- By WWI, large slices of the middle and upper classes, as well as portions of the working class, had ceased to believe in universal suffrage—and had acted on their beliefs
>- In the South, blacks and many poor whites had been evicted wholesale from electoral politics

## 
>- In the North and West, exclusions were on a smaller scale, but still numerous: 
>	+ depending on the state or city in which he lived, a man could be kept from the polls because:
>		+ he was an alien
>		+ a pauper
>		+ a lumberman
>		+ an anarchist
>		+ did not pay taxes or own property
>		+ could not read or write
>		+ had moved from one state to another in the past year
>		+ had recently moved from one neighborhood to another
>		+ did not possess his naturalization papers
>		+ was unable to register on the third or fourth Tuesday before an election
>		+ could not prove that he had canceled a prior registration
>		+ been convicted of a felony, or been born in China or on an Indian reservation
>- It can be no surprise, in light of this legal history, that turnout at elections dropped during the latter half of this period
>- **Voting was not for everyone**

## Root Causes of regression
>- Those who wielded economic and social power in the rapidly changing late nineteenth century found it difficult to control the state (which they increasingly needed) under conditions of full democratization
>- In the South, the abolition of slavery, coupled with the beginnings of industrialization and the com-pelling need for a docile, agricultural labor force, created pressures that overwhelmed fledgling democratic institutions
>- In the North and West, the explosive growth of manufacturing and of labor-intensive extractive industries generated class conflict on a scale that the nation had never known
>- As Max Weber noted long ago, it is during periods of rapid economic and technological change that class becomes most salient and class issues most prominent
>- **The United States was not the only country whose political institutions were profoundly shaken by the stresses of industrialism**

## Racial Hostility
>- Equally critical was the fact that the threatening lower orders consisted largely of men who were racially different or came from different ethnic, cultural, and religious back- grounds
>- What transpired in the South seems unimaginable in the absence of racial hostility and prejudice
>- The changes in voting laws in the North and the West were made possible, and shaped, by the presence of millions of immigrants and their children, indeed by the very foreignness of Jews and Chinese, of the Irish and Italian Catholics, of Indians and Mexicans
>- **It was the convergence of racial and ethnic diversity with class tension that fueled the movement to “reform” suffrage**
>- Note: The wartime conditions that commonly spawned pressures for franchise expansion simply were not present

## North and South Differences
>- The parallels between North and South, of course, ought not be overdrawn
>	+ What transpired in the southern states was far more draconian, sweeping, and violent
>	+ The disfranchisement was massive rather than segmented, the laws were enforced brutally, and they were always administered with overtly discriminatory intent
>- In New York and Massachusetts, an illiterate immigrant could gain the franchise by learning to read; for a black man in Alabama, education was beside the point, whatever the law said
>- That the redemption of the North was far milder than the parallel movement in the South was testimony not only to the significance of race but also to differences in the regions’ social structures and political organizations
>	+ Northern society was too fluid, heterogeneous, and urban to permit the successful imposition of a project as sweeping as the Mississippi plan
>	+ Moreover, the existence of an already competitive party system, with elite and middle-class elements supporting each party, meant that efforts at wholesale disfranchisement (as was contemplated in New York in the 1870s) were certain to encounter fierce resistance and likely to meet defeat
>- The ability of the dominant parties to integrate and incorporate many working-class and immigrant voters made mass disfranchisement less necessary: the Democratic Party in the North (unlike the heavily black Republican Party in the South) did not threaten the established order

## Legal Restrictions had an effect
>- Both North and South, however, the legal contraction of the franchise made a difference
>- Millions of people (most of them working class and poor) were deprived of the right to vote in municipal, state, and national elections
>	+ Their exclusion from the electorate meant that the outcomes of innumerable political contests were altered
>	+ different policies were put into place
>	+ different judges appointed
>	+ different taxes imposed
>- **Many of the core institutions of the modern American state—institutions built and solidified between Reconstruction and World War I were shaped and accepted by a polity that was far from democratic**

## Skipped pages 127-136

## Women’s Suffrage

## Why woman should vote?
Women did not seem (to men) to be endangered by their inability to vote
Nowhere did the enfranchisement of women seem likely to vest Republicans or Democrats with any discernible partisan advantage
Legal structure
>- In 1872, Virginia Minor sued a St. Louis registrar who prevented her from registering to vote. She Claimed:
>	+ They infringed on Virginia Minor’s right of free speech, which was protected by the First Amendment
>	+ they contravened the Fourteenth Amendment’s command that states not abridge the "privileges or immunities" of citizens of the United States.
>- Voting, the Minors claimed, was one of those privileges.
>- Although the argument was a coherent one, the justices of the Supreme Court unanimously disagreed.
>- **Upholding a lower court decision, they ruled in 1875 that suffrage was not coextensive with citizenship and thus that states possessed the authority to decide which citizens could and could not vote**

## The era of maturity
>- Suffragists lived in an era when a righteous cause–the abolition of slavery– that had triumphed over ferocious, entrenched opposition
>- They had witnessed not only the end of slavery but also an extraordinary transformation of popular views and laws regarding Black suffrage
>	+ within a decade, an idea supported only by those on the fringes of politics had acquired the backing of the Republican Party and then been embedded in the Constitution

## No Federal Action
In 1882, both houses of Congress appointed select committees on women’s suffrage, each of which recommended passage of an amendment.
The amendment was finally brought to a vote on the Senate floor, where, to the great disappointment of suffragists seated in the galleries, it was decisively defeated in January 1887 by a margin of thirty-four to sixteen (with twenty-six abstentions), a far cry from the two-thirds positive vote required for passage
No southern senator voted in favor of the amendment, while twenty-two voted against it
**After 1893, no congressional committee reported it favorably until late in the Progressive era**

## State action
Although the issue was debated in numerous constitutional conventions, and referenda were held in eleven states (eight of them west of the Mississippi) between 1870 and 1910, concrete gains were few
The territory of Wyoming enfranchised women in 1869, a policy affirmed at statehood in 1889; Utah did the same in 1870 and 1896 (interrupted by a brief period when the federal government stripped Utah’s women of the suffrage as a curious step in its effort to rid the territory of polygamy); and Idaho and Colorado granted suffrage to women in the mid-1890s

## Partial enfranchisement
A significant number of locales–states, counties, and municipalities–where partial suffrage was adopted, permitting women to vote in municipal elections, on liquor licensing matters, or for local school boards and on issues affecting education
The most common form of partial enfranchisement involved schools: legislatures, recognizing women’s responsibility for childrearing, as well as their education experience, responded to pressure from the suffrage movement by permitting women to vote on matters affecting schooling
Nearly all state legislatures considered adopting laws of this type, and by 1890, more than twenty states had done so

## Challenges for the Suffragists
Many women themselves were either opposed, or relatively indifferent, to their own enfranchisement.
The demand for suffrage was most resonant among middle-class women, women from families engaged in the professions, trade or commerce, and educated women who lived in cities and developing towns
These were the women whose experiences and desires clashed most directly with traditional norms and who were most likely to seek the independence, autonomy, and equality that enfranchisement represented
Farm women, living in greater isolation and in more traditional social structures, were less responsive to calls for suffrage as well as more difficult to mobilize into collective action

## Additional challenges
The political pressure that suffragists could exert thus was limited by their numbers, too limited to overcome the entrenched ideological and psychological resistance of many male voters and politicians.
The campaigns for suffrage generated organized opposition from some interest groups
Machine politicians also were dubious about women’s suffrage–in part for cultural reasons and in part because they always sought to keep the electorate as manageable as possible
Conservative members of the economic elite who took seriously the proposition that women would promote egalitarian social reforms

## Win some, lose some
>- The South was particularly resistant to enfranchising women
>- But, the West was unusually receptive.
>	+ All of the states that fully enfranchised women in the nineteenth century were west of the Mississippi, as were most states that held referenda on the issue
Western suffrage
>- What seems to have tipped the balance in a handful of western states (as well, perhaps, as in western states that dominated the first twentieth-century wave of suffrage victories) was a combination of several additional ingredients.
>	+ a more fluid pattern of party competition
>	+ included a highly visible number of working-class transients who labored in mining, railroading, and agriculture.
>	+ Since this group consisted overwhelmingly of single males, the enfranchisement of women offered discernible political benefits to the settler population at the expense of workers in extractive industries

## Western suffrage
Most western states between 1850 and the 1890s did not experience the massive growth of an industrial working class that triggered such an antidemocratic reaction in the East and Midwest
The region’s swing against democracy was more mild and emotionally focused on the largely male Chinese population

## _Doldrums and Democracy_
>- In October 1893, the _New York Times_ declared in an editorial that "the cause of woman suffrage does not seem to have made the least progress in this part of the country in the last quarter of a century, if indeed it has not lost ground."
>	+ Only a tiny portion of the nation’s women was fully enfranchised
>	+ interest was flagging in many states
>	+ most of the women who were entitled to vote in school board elections did not show up at the polls
Organization
National American Woman Suffrage Association (NAWSA) – combination of two organizations in 1890
By the end of the 1890s, NAWSA had created branches in every state, founded hundreds of local clubs, generated large quantities of literature, and was pressuring politicians everywhere
NAWSA also began to target and raise funds from wealthy, upper-class women, some of whom for the first time were lending their support to the movement

## Shifts in ideology
>- Shifts in ideology–or at least by shifts in the emphases placed on various arguments
>	+ Mirroring the broader middle-and upper-class disenchantment with democracy, suffragists placed less weight on equal rights arguments, which implied that everyone, male and female, should possess the right to vote
>	+ They stressed instead the more palatable essentialist theme that feminine qualities would be a welcome addition to the polity

## Essentialist theme
Essentialist emphasis was reinforced by the increasingly common claim that women had distinct economic and social interests that could only be protected by possession of the right to vote.
White middle-class suffragists placed new weight on the argument that the enfranchisement of women would compensate for and counterbalance the votes of the ignorant and undesirable

## Changing strategies
In the South, of course, the American Republic was thought to be threatened not by immigrants but by Blacks
It was argued that "the medium through which to retain the supremacy of the white race over the African"
In both the North and South, the notion that women were the antidote to undesirable voters led many suffragists, including Stanton, to join the conservative chorus calling for literacy tests as a means of shaping the electorate
**Suffragists effectively abandoned the principle of universal suffrage in favor of increasingly popular class-based limitations on electoral participation**

## "the doldrums"
The period from 1896 to 1910 came to be known among suffragists as "the doldrums"
Although the issue was raised repeatedly in state legislatures and constitutional conventions, there were no new additions to the suffrage column.
In the South, the statistical argument was simply no match for the frenzied political circus that was disfranchising Blacks and poor whites in one state after another
In the North, the parallel push for suffrage for educated women collided head-on with the powerful middle-and upper-class desire to shrink the electorate

## Internal contradictions
Whatever its statistical validity, the anti-Black, anti-immigrant, and anti–working class argument in favor of women’s suffrage was inescapably weakened by its own _internal contradictions _
An **antidemocratic** argument in favor of enlarging the franchise could neither overwhelm nor outflank the simpler, more consistent conservative view that the polity should be as _narrowly circumscribed_ as possible

## Coalition building
The first decade of the twentieth century proved to be less a period of failure than of fruitful stock-taking and coalition building
The movement became socially and ideologically more diverse, attracting both elite and working-class supporters to complement its middle-class base
Female workers
By 1900, roughly one fifth of the labor force was female, and many of these women held poorly paid, semiskilled jobs; in 1905, there were 50,000 women in New York’s garment industry alone
New emphasis on working women had both ideological and pragmatic attractions for suffragists.
Female workers were described as "exemplars of independent womanhood"
They were also vulnerable and exploited victims of industrial capitalism whose plight readily tapped the broad impulses of Progressive-era social reform

## Class and gender
That suffrage would never be achieved until it had gained the electoral support of working-class men–which meant emphasizing class as well as gender issues
Working women themselves, as well as their activist leaders, displayed new interest in acquiring the right to vote
This arose in part because of their difficulty unionizing and winning workplace conflicts
**They were convinced that state intervention could ameliorate their working conditions and that such intervention would be forthcoming only if they were enfranchised**

## State-level Victories
Thanks in part to this convergence of working-class interest in suffrage with the suffragists’ interest in the working class, the campaign for women’s suffrage became a mass movement for the first time in its history after 1910
The movement also began to win some new victories. Washington permitted women to vote in 1910, followed by California in 1911, and Arizona, Kansas, and Oregon the following year; Illinois, in 1913, decided to allow women to vote in presidential elections and for all state and local offices not provided for in its constitution; and the next year, Montana and Nevada adopted full suffrage.
In 1912, Congress expressly authorized the territory of Alaska to enfranchise women if its legislature so chose

## New allies
In 1910, President William H. Taft agreed to address the annual convention of NAWSA
That same year, a petition favoring a federal amendment, signed by more than 400,000 women, was presented to Congress
In 1912, the Progressive Party endorsed women’s right to vote, and in March 1913, Woodrow Wilson’s inauguration was partially eclipsed by a suffrage parade of 5,000 women in Washington
The following year, a Senate committee reported favorably on a federal amendment, and for the first time in decades a draft amendment was brought to the floor of Congress for a vote
But, opposition remained strong, particularly in the eastern half of the country.

## Southern resistance
By the latter years of the Progressive era, African Americans had been successfully disfranchised throughout the South, and most whites were intent on keeping it that way
Politicians were loath to tinker at all with electoral laws, and they feared that _Black women might prove to be more difficult to keep from the polls than Black men_ –because Black women were believed to be more literate than men and _more aggressive about asserting their rights_ , and also because women would be unseemly targets of repressive violence
Many Southerners were convinced that a federal amendment would open the doors to **Washington’s intervention in elections, to enforcement–so glaringly absent–of the Fifteenth Amendment** and any subsequent amendment that might appear to _guarantee the voting rights of Black women_

## The Nineteenth Amendment
President Woodrow Wilson declined to endorse women’s suffrage, evasively reiterating his view that suffrage was a state issue
The national Democratic Party was similarly unresponsive
The Republican platform of 1916, in contrast, endorsed the cause, albeit in watered-down language
1916 election
>- The 1916 elections set in motion two distinctive partisan dynamics that had surfaced periodically in suffrage struggles since the 1840s
>	+ the first resulted from the partial enfranchisement of women: **some women already could vote in all elections, and many could vote in some elections**
>	+ such circumstances gave women leverage to reward or punish politicians because of their (or their party’s) stance on the Nineteenth Amendment
>	+ The second dynamic was that of the "endgame," the dynamic of possible or impending victory: **once it seemed likely or even possible that women’s suffrage eventually would be achieved** , either nationally or in an individual state, **the potential political cost of a vote against enfranchisement rose dramatically**

## World War I
In 1917, the United States entered World War I
The most critical impact of the war was the opportunity it gave suffragists to contribute to the mobilization
The age-old argument that women should not vote because they did not bear arms was no longer applicable
"essential to the successful prosecution of the great war of humanity in which are engaged. . . . We have made partners of the women in this war. Shall we admit them only to a partnership of sacrifice and suffering and toll and not to a partnership of privilege and of right? This war could not have been fought . . . if it had not been for the services of women."

## Woodrow Wilson
Federal success
The suffragists’ able handling of the war crisis, coupled with continuing political pressure on Congress and the president, was rewarded in January 1918
The president, in an extraordinary address, announced his support of a federal suffrage amendment "as a war measure"
The next day, the House of Representatives voted in favor of the Nineteenth Amendment: the victory was won by one vote, with the Democrats splitting almost evenly while more than 80 percent of Republicans voted favorably.

## Convincing the Senate
The Senate, where antisuffragist southern Democrats constituted a proportionally larger bloc, took an additional year and a half to endorse the amendment
After months of relentless political pressure and careful targeting of Republican and Democratic holdouts, the Senate–by a large Republican majority and a small Democratic one– finally came on board in the summer of 1919
State Ratification
Ratification depended on winning virtually every state outside of the South and the border states
Antisuffragists geared up for battle, denouncing the Nineteenth Amendment as a violation of states’ rights and a giant step toward socialism and free love
To no one’s surprise, the South remained recalcitrant
**On August 18, 1920, Tennessee, by a margin of one vote, became the thirty-sixth state to vote positively on the amendment; a week later, after ratification had been formally certified, the Nineteenth Amendment was law**

## The Nineteenth Amendment
The Nineteenth Amendment
Section 1: **The right of citizens of the United States to vote shall not be denied or abridged by the United States or by any State on account of sex**
Section 2: **Congress shall have power to enforce this article by appropriate legislation**

## After ratification
It is a well-known irony in American history that politics did not change very dramatically after women were enfranchised
The electorate nearly doubled in size between 1910 and 1920, but voting patterns and partisan alignments were little affected
**Women, moreover, did not rush out to vote in huge numbers: electoral turnout was even lower among women than among men**

## How things changed
Political life in the 1920s was not nearly as vibrant or energetic as it had been in the 1890s or the latter years of the Progressive era; despite the identification of women with social reform, reforms were few during the first decade that women could vote
New issues, particularly those affecting women and children, were injected into the political arena, even if concrete reforms were slow to materialize
The social welfare programs of the 1930s were colored by the concerns of the female electorate and often promoted by women who had cut their political and organizational teeth in the suffrage movement
Franklin Roosevelt’s appointment of Frances Perkins as secretary of labor (and as the first woman to hold a cabinet position) would not have happened without the Nineteenth Amendment

## Southern power
The suffragists’ prediction that the enfranchisement of women would not jeopardize white supremacy in the South proved to be on the mark
Although some (but not many) Black women were able to register to vote, the Democratic Party remained firmly in power, segregation and Black disfranchisement persisted, and the federal government steered clear of voting rights issues for another four decades
**Sex, thus, did not prove to be a significant dividing line in the American electorate** : some gender gaps in voting did occur in the early years (as well as more recently), but they were not large, and few issues sharply divided men and women.

## How life changed
Women certainly were empowered by enfranchisement, and their lives consequently (if gradually) may have changed in a host of different ways, but they tended to vote for the same parties and candidates that their husbands, fathers, and brothers supported
Class, race, ethnicity, and religion remained the more salient predictors of a person’s voting behavior
Why was there opposition
The very absence of dramatic change after 1920 inescapably leaves one wondering what the adamant resistance was all about
Why, given the rather placid outcome, did so many men oppose women’s suffrage for so long?
Why did it take women seventy years after Seneca Falls to become enfranchised?

TOWARDS UNIVERSAL SUFFRAGE -- AND BEYOND
THE QUIET YEARS
CHAPTER 7
TO BE ADDED
Racial Tensions
The South was a cauldron of racial tension in the 1950s
African Americans pressed forward against the boundaries of America’s caste system, demanding an end to social segregation and second-class citizenship
Fighting for Rights
Black citizens marched, rallied, boycotted buses, wrote petitions, and filed lawsuits to challenge the Jim Crow laws that had kept them in their place for more than half a century
The widespread resistance to integration only underscored the Black community’s need for political rights, but throughout the 1950s their efforts to vote were thwarted more often than not
Politics of the 1950s
Liberal Democrats in Congress were eager to take action–at least to implement the recommendations of Truman’s Commission on Civil Rights–but their influence was offset by the power of southern Democrats
Republicans were similarly torn: while the desire to court Black voters reinforced the party’s traditional pro–civil rights principles, many Republicans also hoped to make inroads into the solid South by winning over white southern voters
Civil Rights Act 1957
The first civil rights bill passed by Congress in more than eighty years
It was a modest piece of legislation, so modest that it was roundly criticized by African-American activists
The bill created a national Civil Rights Commission, elevated the Civil Rights section into a full-fledged division of the Justice Department, and authorized the attorney general to seek injunctions and file civil suits in voting rights cases
Ineffectual legislation
Well-intentioned as the bill surely was, it had few teeth and little impact
The Justice Department was sluggish in initiating suits, southern federal judges were sometimes unreceptive, and the entire strategy of relying on litigation inescapably meant that progress would be slow
The ineffectiveness of the bill led to the passage in 1960 of a second Civil Rights Act, stronger than the first, but conceptually similar and still modest in its reach
Political Temperature
The Civil Rights Acts of 1957 and 1960 were bipartisan compromises constructed to appease competing political interests, but it was apparent that difficult choices loomed on the horizon
The political temperature was soaring in the South
The growing militancy of the Black freedom movement only stiffened the opposition
The Fight
The governors of Alabama and Mississippi refused to desegregate their universities
Voting districts were gerrymandered to dilute the influence of Blacks who did manage to register
Freedom riders were beaten and their buses burned
Police arrested protestors by the thousands
Bombs were tossed into Black churches
Activists were occasionally murdered in cold blood
XXIV Amendment
Twenty-fourth Amendment was ratified with relatively little opposition; and Black registration in the South rose to more than 40 percent by 1964
Section 1:  __The right of citizens of the United States to vote in any primary or other election for President or Vice President for electors for President or Vice President, or for Senator or Representative in Congress, shall not be denied or abridged by the United States or any State by reason of failure to pay any poll tax or other tax__
Section 2:  __The Congress shall have power to enforce this article by appropriate legislation__
Civil Rights Act 1964
Conflict in the South continued
The Kennedy administration in 1963 drafted an omnibus civil rights bill designed to give strong federal support to equal rights, although it said little about voting rights per se
Pres. Kennedy did not live to witness the passage of his civil rights bill, but his successor, Lyndon Johnson, seized the moment after Kennedy’s assassination to obtain the bill’s passage as a tribute to the late president
Voting Rights Act
Johnson himself was elected to the presidency in 1964 with an enormous popular vote, offering the first southern president in a century the opportunity to complete the Second Reconstruction
He was personally sympathetic to the cause of Black suffrage, bidding for a place in history, and prodded by the nationally televised spectacle of police beatings and arrests of peaceful, prosuffrage marchers in Selma, Alabama
Pressing for change
Johnson went to Congress in March 1965 to urge passage of a national Voting Rights Act.
"The outraged conscience of a nation" demanded action, "It is wrong–deadly wrong–to deny any of your fellow Americans the right to vote." "it is really all of us, who must overcome the crippling legacy of bigotry and injustice. And we  _shall _ overcome." he told a joint session of Congress.
New Constituency
Johnson’s words, spoken to a television audience of seventy million and to a somber, hushed Congress that interrupted him forty times with applause, were sincere, principled, and moving
The president also knew that the Democrats’ political balancing act was over: with the Civil Rights Act of 1964,  __the party had decisively tilted away from the white South and toward Black voters__ , and now it was going to need as many Black voters as possible to have a chance of winning southern states
The Voting Rights Act
Designed as a temporary, quasi>- emergency measure, the act possessed an automatic "trigger" that immediately suspended literacy tests and other "devices" (including so-called good character requirements and the need for prospective registrants to have someone vouch for them) in states and counties where fewer than 50 percent of all adults had gone to the polls in 1964; the suspensions would remain in force for five years
The act authorized the attorney general to send federal examiners into the South to enroll voters and observe registration practices
Section 5
To prevent the implementation of new discriminatory laws, section 5 of the act prohibited the governments of all affected areas from changing their electoral procedures without the approval (or "preclearance") of the civil rights division of the Justice Department or a federal court in Washington
States could bring an end to federal supervision only by demonstrating to the federal court that they had not utilized any discriminatory devices for a period of five years
Passing the law
The Voting Rights Act was passed by an overwhelming majority, as moderate Republicans joined with Democrats to carry out what Johnson called the "tumbling" of "the last of the legal barriers" to voting
Some conservative Republicans and southern Democrats voted negatively, but recognizing the inevitability of the bill’s triumph and the political wisdom of supporting it, forty southern congressmen voted favorably
Immediate impact
The legislation had an immediate impact
In Mississippi, Black registration went from  _less than 10 percent_  in 1964 to almost  _60 percent_  in 1968; in Alabama, the figure rose from  _24 percent _ to  _57 percent _
In the region as a whole,  __roughly a million new voters were registered__  within a few years after the bill became law, bringing African-American registration to a record 62 percent
Milestone law
The essence of the act was simply an effort to enforce the Fifteenth Amendment, which had been law for almost a century
Racial barriers to political participation had been a fundamental feature of American life, and resistance to racial equality was deeply ingrained; so too was resistance to federal intervention into the prerogatives of the states
__Why did the country finally overcome its obstacles to pass the VRA?__
Renewing the VRA
>- In 1970, despite significant reluctance in the Nixon administration and congressional jockeying to weaken the measure, the bill was renewed for five years
>	+ the ban on literacy tests was extended to all states
>- In 1975, the act was extended for an additional seven years, and its reach enlarged to cover "language minorities," including Hispanics, Native Americans, Alaskan Natives, and Asian American
>- In 1982, despite the Reagan administration’s anti-civil rights posture, the act’s core provisions were extended for an additional twenty-five years
>- Reauthorized on a unanimous Senate vote and a 390-33 House vote in 2006 for 25 more years
Transformation of Politics
The debates surrounding these renewals–and they were substantial–were grounded in a new partisan configuration that in part was a consequence of the Voting Rights Act itself
By the late 1960s, all southern states contained a large bloc of Black voters whose loyalty to the Democratic Party had been cemented by the events of the Kennedy and Johnson years
Since these voters constituted a core Democratic constituency, Democratic politicians, even within the South, generally supported efforts to shore up Black political rights
At the same time, conservative white Southerners, joined by some migrants into the region, flocked to the Republican Party, reviving its fortunes in the South and becoming a critical conservative force in the national party.
VRA in the Courts
>- _South Carolina v. Katzenbach_  (1966)>	+ Voting Rights Act "are a valid means for carrying out the commands of the Fifteenth Amendment."
>- By the end of the 1960s, thus, two precepts had been clearly and irretrievably etched into federal law
>	+ The first was that  __racial barriers to the exercise of the franchise, whether simple or sophisticated, direct or indirect, were illegal__
>	+ The second was that  __Congress, backed by the courts, possessed the authority to take vigorous, even extraordinary, measures to dismantle any such racial barriers __
Warren Court
The Warren Court came to see itself as the guardian of formal democratic rights, and it fashioned the equal protection clause of the Fourteenth Amendment into a formidable weapon with which to protect the ability of citizens to participate in democratic processes
There was always conflict about the breadth of the franchise and that those  _who possessed it _ could not necessarily be counted on to extend the right to others
Faced with this reality, it made sense for an insulated institution such as the Court to defend what it believed to be a  __fundamental element of American politics __
Strict Scrutiny
Any "statutes which deny some residents the right to vote" had to come under the "strict scrutiny" of the Court  _Kramer v. Union Free School District _ (1969)
"statutes distributing the franchise constitute the foundation of our representative society."
Strict scrutiny meant that any restriction on the franchise had to be "necessary to promote a compelling state interest."
Ending Literacy Tests
Court previously held that literacy tests were constitutional as long as they were not administered in a racially discriminatory fashion.
In  _Gaston County, N.C. v. United States_  (1969), the Court ruled that literacy tests were unacceptable in locales where schools had been segregated
_Oregon v. Mitchell _ (1970) Blacks, as well as Native Americans and other minorities, received unequal and inferior educations in many locales in and out of the South, and this bias in educational opportunities hindered their ability to pass literacy tests
High rates of interstate migration, moreover, meant that literacy tests administered in states such as Arizona and New York could have the effect of disfranchising African Americans trained in segregated southern schools
Residency Requirements
The federal government’s first effort to remove yet another obstacle to enfranchisement: lengthy residency requirements
Although some states had shortened their requirements, one year was still the norm
The impact of these laws according to one estimate, they kept fifteen million people from voting in the 1964 elections
With little fanfare or controversy, the 1970 VRA renewal prohibited the states from imposing more than  __a thirty-day residency requirement in presidential elections__ ; at the same time, it mandated that those who had  _relocated less than thirty days prior to an election could cast absentee ballots in their previous place of residence _
"If young men are to be drafted at eighteen years of age to fight for their Government they ought to be entitled to vote at eighteen years of age for the kind of government for which they are best satisfied to fight."
Senator Arthur Vandenberg
Age to vote
Since the nation’s founding, a voting age of twenty-one–a carryover from colonial and English precedents–had been a remarkable constant in state laws governing the franchise
Polling data indicated that most Americans favored a reduction in the voting age (support rose dramatically between 1939 and 1952)
Vietnam War
The unpopularity of the Vietnam war spawned a widespread draft resistance movement, mass protests by college students, and an alarming radicalization of the young
In the political climate of the mid>- and late 1960s, the issue of eighteen-, nineteen-, and twenty-year-olds voting acquired an unprecedented urgency
Their lack of enfranchisement served, rhetorically at least, to  __underscore the absence of democratic support for the war __ and to legitimize resistance to the draft
Slipping in the change
The  _New York Times _ endorsed an age reduction on the grounds that " _young people . . . are far better prepared educationally for the voting privilege than the bulk of the nation’s voters have been through much of its history_ "
In the spring of 1970, with little advance notice, legislators added a proposal for reducing the voting age, in all elections, to the amendments being prepared to the Voting Rights Act
Two-tiered rules
In  _Oregon v. Mitchell_ , the court ruled that Congress could legislate the age for federal elections, but not state elections
The prospect of a two-tiered age limit was an administrative and logistical nightmare for state election officials
Faced with this crisis, Congress moved expeditiously to rectify the mess that it had helped to create
Amendment XXVI
Senator Jennings Randolph introduced a proposal for a constitutional amendment that barred the United States or any state from denying or abridging the right to vote of any citizen aged eighteen or over on account of age
In March 1971, the Senate, with no dissenting votes, approved the amendment
Within a few weeks, the House had done the same, with negative votes cast by only nineteen members, mostly conservative Republicans or southern Democrats
State legislatures then rushed to ratify the amendment
By the end of June, thirty-eight states had done so, and the Twenty-sixth Amendment was law
__The ratification process was by far the most rapid in the history of the republic __
National Franchise
What occurred in the course of a decade was not only the re-enfranchisement of African Americans but the abolition of nearly all remaining limits on the right to vote
The total number of new voters added to the electorate cannot be counted with precision, but the figure was surely in excess of twenty million
__The Voting Rights Acts, coupled with a succession of Supreme Court decisions, effectively brought to a close the era of state control over suffrage__
National voting rights
The political leaders of the 1960s found themselves thinking through the issue of voting rights in a manner unparalleled since Reconstruction
If the polity was going to be democratized, it would require action by the national government, in the name of the nation’s publicly professed values
Equal Protection
Court’s discovery of the  __applicability of the equal protection clause __ to voting rights represented the Court’s own embrace of the internal logic of suffrage reform
If discriminating against Blacks was wrong–and it was clearly proscribed by the Fifteenth Amendment–so too was discriminating against the  _very poor_ , the  _propertyless_ , the  _mobile_ , and the  _Spanish-speaking _
The Court’s use of the equal protection clause was a means of extending the ban on racially-grounded disenfranchisement stated explicitly in the Fifteenth Amendment to  _other forms of discriminatory disfranchisement_  not expressly mentioned in the Constitution
DC voting rights
Residents of the capital remained unsuccessful in their attempts to gain voting representation in Congress
__They had been granted electoral votes in presidential elections in 1961, thanks to the Twenty-third Amendment to the Constitution __
In 1978, a constitutional amendment was approved by Congress that would have granted Washington two senators as well as voting representatives in the House
Conservatives around the nation (and particularly in the South) opposed the measure; when the seven-year window for ratification closed in 1985, the D.C. Voting Rights Amendment had been endorsed by only sixteen of the needed thirty-eight states
_What rights should residents of DC have in terms of voting & representation?_
