---
title: "The Right to Vote - Part II"
author: "Prof. Jonathan Cervas"
date: "Updated: `r format(Sys.time(), '%B %d, %Y')`"
output: 
 beamer_presentation:
  keep_tex: false
 md_document:
  variant: gfm
 html_document:
  theme: yeti
  highlight: textmate
 pdf_document:
  keep_tex: false
classoption: aspectratio=169
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
## rmarkdown::render('/Users/cervas/Library/CloudStorage/GoogleDrive-jcervas@uci.edu/My Drive/GitHub/teaching/classes/class-cmu-84-352/lecture-slides/the-right-to-vote-lecure-slides/The-Right-to-Vote-Part-II.Rmd', output_format = 'all')
```


## END

END

## Rights under attack

- Even before Reconstruction came to a quasi-formal end in 1877, Black voting rights were under attack

- Elections were hotly contested, and white Southerners, seeking to “ _redeem_ ” the region from Republican rule, engaged in both legal and extralegal efforts to limit the political influence of freedmen

- In the early 1870s, both in the South and in the border states, districts were gerrymandered, precincts reorganized, and polling places closed to hinder Black political participation

- Organizations such as the Ku Klux Klan mounted violent campaigns against Blacks who sought to vote or hold office, as well as their white Republican allies

## Enforcement & KKK Acts

- In May 1870, stretching the limits of its constitutional powers, Congress passed an Enforcement Act that made **interference with voting a federal offense, punishable in federal courts** 
  — federal courts were presumed to be more reliable than state courts

- It also passed the Ku Klux Klan Act, which, among its provisions, authorized the president to **deploy the army to protect the electoral process**

## Losing enthusiasm

- By the mid-1870s, many northern Republicans, including President Grant, had lost their enthusiasm for policing the South

- Preoccupied with an economic depression and labor conflict in the North, they wearily drifted toward a “ _let alone policy_ .”

- In September 1875, one Republican newspaper referred to the Fourteenth and Fifteenth Amendments as “dead letters”

## Southern Redeemers

- The Redeemers who were gaining power throughout the South in the 1870s had goals that were at once _political_, _social_, and _economic_

- Most immediately they sought to drive the Republicans from power and elect Democrats, an objective hard to attain in a fully enfranchised South.
  - Limiting Black voting therefore was a means to a end.

- Keeping freedmen from the polls was also a means of rebuffing broader claims to equality, a way of returning Blacks to “ _their place_ ,” of making clear that, whatever the Fourteenth Amendment said, **Blacks did not enjoy full citizenship**

## Rising Redeemers

- The pace of Redemption was quickened by the presidential election of 1876 and the subsequent removal of the last federal troops from the South.

- In 1878, Democrats won control of both houses of Congress for the first time in twenty years

- The Redeemers, who controlled most state legislatures, continued to try to shrink the Black (and opposition white) electorate through gerrymandering, registration systems, complicated ballot configurations, and the secret ballot (which served as a de facto literacy test)

## Shifting partisan winds

- National elections were extremely close and fiercely contested in the late 1870s and 1880s
  - congressional majorities were unstable
  - in 1884 Grover Cleveland became the first Democratic president since before the Civil War

- In the eyes of many Republicans, the Democrats’ success, their ability to wield national power, was illegitimate, dependent on wholesale violations of the Fifteenth Amendment in the South

## Illegitimate power

- In its 1888 platform, the Republicans charged “ _that the present Administration and the Democratic majority owe their existence to the suppression of the ballot by a criminal nullification of the Constitution and laws of the United States._ ”

- After they were victorious in that year’s elections, the Republicans had a chance to do something about it: they had won the presidency and control of both houses of Congress
  - They proposed the _Federal Elections Bill_
  - a small number of petitions to federal circuit courts could lead to the appointment of federal supervisors were entrusted with:
    - attending elections, inspecting registration lists, verifying information given by doubtful voters, administering oaths to challenged voters, preventing illegal immigrants from voting, and certifying the count
  - the bill gave federal officials and courts the power to overturn election results that had been declared and certified by state officials

## Federal Elections Bill

- The Republicans certainly stood to gain from fair elections in the South and from less corrupt elections in some Democratically run northern cities

- Those who voted for the enforcement acts of the 1870s (which were scaled back by the Courts), were enraged that the hard-won victories of war and Reconstruction were being undermined by fraud and violence.

- The Democrats, of course, fiercely opposed the bill, denouncing it as “a scheme to rob the people of the States of the dearest right of American citizenship.”

- Losing 35 to 24 with 19 abstentions, the federal government backed away from a significant expansion of its role in shaping electoral law and guaranteeing democratic rights
  - this occurred not only because the nation and the Congress were divided, but also because of back-door political dealing and accidents of timing

## Federal Involvement

- This signaled to the South that the federal government was not prepared to act energetically to guarantee the voting rights of Blacks

**Whatever the Fourteenth and Fifteenth Amendments said on paper, the right to vote was back in the hands of the states**

Not until the 1960s, when the Lodge Force Bill was reincarnated as Lyndon Johnson’s _Voting Rights Act_ , did Congress again seriously consider federal intervention in southern politics

## Rollback

- The year 1890 also marked the beginning of systematic efforts by southern states to disfranchise Black voters legally

- Democrats chose to solidify their hold on the South by modifying the voting laws in ways that would exclude African Americans without overtly violating the Fifteenth Amendment.

- Experiments with these legal strategies had occurred in the 1870s and 1880s, but it was between 1890 and 1905 that they became the primary weapon in enforcing and institutionalizing Redeemer rule

- White Democrats turned back the clock on the broadly progressive franchise provisions that had been etched into most Reconstruction-era state constitutions

## Mississippi

- Passed provisions that would remove Blacks from Mississippi political life while technically adhering to the Fifteenth Amendment

- These provisions included a sharp increase in the _residency_ requirement (“the negro is . . . a nomadic tribe,” opined the state’s attorney general), the institution of a two-dollar _poll tax_ , and the imposition of a _literacy test_ that required potential voters to demonstrate that they could understand and interpret the Constitution

**In short order, other states followed suit**

## Suppression

- The overarching aim of such restrictions, usually undisguised, was to keep poor and illiterate Blacks—and in Texas, Mexican Americans—from the polls.

- Literacy tests served that goal well, since 50 percent of all Black men (as well as 15 percent of all whites) were illiterate, and even small tax requirements were a deterrent to the poor

- It was during this period that the meaning of poll tax shifted: where it once had referred to a head tax that every man had to pay and that sometimes could be used to satisfy a taxpaying requirement for voting, it came to be understood as a _tax that one had to pay in order to vote_

## Uneven enforcement

- Small errors in registration procedures or marking ballots might or might not be ignored _at the whim_ of election officials; taxes might be paid easily or only with difficulty

- Discrimination also was built into literacy tests, with their “_understanding_” clauses: officials administering the test could, and did, judge whether a prospective voter’s “_understanding_” was adequate

_That, exactly, is what this Convention was elected for—to discriminate to the very extremity of permissible action under the limitations of the Federal Constitution, with a view to the elimination of every negro voter who can be gotten rid of, legally, without materially impairing the numerical strength of the white electorate._ - future Senator Carter Glass

## Grandfather Clause

- Discrimination, as well as circumvention of the Fifteenth Amendment, was also the aim of the well-known grandfather clauses
 - exempted men from literacy, tax, residency, or property requirements if they had performed military service or if their ancestors had voted in the 1860s.
 - The first southern grandfather clause was adopted in South Carolina in 1890; with exquisite regional irony, it was modeled on the anti-immigrant Massachusetts law of 1857

## Anti-white-opposition

- Contrary to twentieth-century images of a monolithic solid South, there was substantial white opposition to new restrictions on the franchise
 - many upcountry whites, small farmers, Populists, and Republicans viewed such laws as a means of suppressing dissent, a self-interested and partisan grab for power by dominant, elite, often Black-belt Democrats
 - This resulted in prolonged and bitter debates about the dangers of “ _reform_ ”

## Effect of new suppression laws

- The laws, of course, worked.

- In Mississippi after 1890, less than 9,000 out of 147,000 voting-age Blacks were registered to vote

- In Louisiana, where more than 130,000 Blacks had been registered to vote in 1896, the figure dropped to an astonishing 1,342 by 1904

## Voting Rates

- Just how many persons were barred from the polls is impossible to determine, but what is known is that both registration and turnout (calculated as the percentage of votes cast divided by the number of men of voting age) dropped precipitously after the electoral laws were reconfigured

- By 1910, in Georgia, only 4 percent of all Black males were registered to vote.

- In Mississippi, electoral turnout had exceeded 70 percent in the 1870s and approached 50 percent in the decade after the Redeemers came to power: by the early twentieth century, it had plummeted to 15 percent and remained at that level for decades.

- In the South as a whole, post-Reconstruction turnout levels of 60 to 85 per-cent fell to 50 percent for whites and single digits for Blacks

**The achievements of Reconstruction had been reversed, and the rollback had restored the southern electorate to—at best—pre–Civil War proportions**

## What this all meant

- The African-American population remained largely disfranchised until the 1960s, electoral participation remained low, and one-party rule by conservative Democrats became the norm

- The nineteenth-century trend toward democratization had been not only checked, but reversed

- The increasingly egalitarian institutions and convictions forged before the Civil War were undermined, while class barriers to electoral participation were strengthened or resurrected

## The North stood by

- All of which took place _without_ great protest from the North
  - Although Republican politicians and newspapers routinely criticized the disfranchising laws, scattered efforts to enforce the Fourteenth Amendment—by reducing the congressional representation of southern states—garnered little support

- The Supreme Court upheld the legality of all of the major techniques of disfranchisement.

- In 1898 it ruled that Mississippi’s literacy test did not violate the Fifteenth Amendment because the law creating the test was not, _on its face_ , designed to discriminate against Blacks

**The North in effect tolerated disfranchisement in the South— in part from weariness, in part due to the partisan interests of the Democratic Party, and in part because Northerners too had been losing faith in democracy**

## END

## The Redemption of the North

Elections in the 1870s-80s

National elections were closely contested; control of Congress changed hands frequently; presidents were elected by razor-thin margins and sometimes with less than a majority of the popular vote

Although party identifications were strong, third parties frequently cropped up and remarkably often gained substantial influence in state and local governments

Issues

The issues animating political life were big ones, sparked by the rapid spread of industrialization, fanned by class and interest-group conflict

The tariff and the money supply (which affected prices and the availability of credit) were issues in every national election

Railroad rates and regulation often dominated state political contests

City dwellers fought over the development and financing of increasingly necessary water, sewer, and transport systems

Issues and conflict

Embedded in all such issues were conflicts over corporate power and uncertainty about the proper role of the state: farmers and shippers pressed the states and Washington to protect them against the predations of railroads that controlled access to markets; workers sought legislation to shorten the hours of labor; small businesses cried out against monopolies; and urban consumers demanded regulation of utility companies

The sale of liquor, for example, was a life-and-death issue in many elections

Politics revolved around the myriad consequences of the increasingly evident triumph of industrial capitalism

Fate of the South

* After 1900—or after the critical election of 1896, which yielded a new and long-lasting partisan alignment
 * The tone of political life shifted, although the dominant issues remained the same
* The fate of the South was settled (removing one key contentious issue from the political arena), the Republican Party securely dominated much of the North-east and Midwest, and third-party rebellions became infrequent
* Electoral turnout fell, North and South, while the major political parties suffered a decline in enthusiasm and loyalty
* The apocalyptic language of late-nineteenth-century politics—a language of crisis and perceived conflict—gave way to a more metallic and optimistic language of problem solving and expertise

Changing country

* Between 1865 and 1900, the United States became the leading manufacturing nation in the world, and its industrial output eclipsed that of agriculture
* When Americans who had come of age in the 1840s and 1850s gazed outward after the Civil War, what they saw was unfamiliar and disturbing:
 * new industries, large and impersonal workplaces, private corporations wielding enormous economic and political power, and economic panics that created new problems such as mass unemployment.
 * They saw abandoned farms, railroads crisscrossing vast stretches of country, and—distressingly—cities of unprecedented size and complexity.

Cities

In 1870, only New York and Philadelphia had populations greater than 500,000;

By 1910, there were eight, three of which contained more than a million people

These cities increasingly were governed by political organizations, or machines, as critics called them, that the traditional elites could not control or even understand

Immigrants and labor

What Americans also witnessed—and apparently feared—was the extremely rapid growth of an immigrant working class.

Interrupted by the Civil War, the flow of immigrants that had begun in the 1840s resumed quickly after the war

the nation’s expanding industries needed labor, and that labor was supplied by men and women from Europe and to a far lesser extent Asia and Mexico.

Immigrants

Between 1865 and World War I, nearly twenty-five million immigrants journeyed to the United States, accounting for a large proportion of the nation’s World War I population of roughly one hundred million

The vast majority of these immigrants were propertyless workers rather than settlers.

The Irish and Germans continued to arrive, joined by growing numbers of southern and eastern Europeans: men and women who did not speak English, whose cultures were alien, and most of whom were Catholic or Jewish.

By 1910, most urban residents were immigrants or the children of immigrants, and the nation’s huge working class was predominantly foreign-born, native-born of foreign parents, or Black

Decline of democracy

Within a few years of passage of the Fifteenth Amendment, a significant segment of the intellectual community was announcing its distrust of democracy and rejecting the claim that suffrage was a right.

The terms of public discussion were being set by men who believed that universal suffrage had failed, that it was neither viable nor desirable in the socially heterogeneous, industrial world of the late nineteenth century

Reforms against suffrage

* Proposals for achieving such a goal began to find their way onto the public agenda in the 1870s and remained there for decades
* Among them were less frequent elections, at-large rather than district voting, increased public accountability for office holders, and state control over key arenas of municipal administration
* Another proposal that garnered considerable attention was to remove public offices from the electoral sphere and make them appointive
 * It was “absurd” to involve the electorate in “the selection of judges and sheriffs, and district attorneys, of state treasurers and attorney-generals, of school commissioners and civil engineers.”

Reforms to strength democracy

Other critics were more optimistic about the possibilities of changing the size and shape of the electorate

Some advocated reinstituting property and tax qualifications or imposing literacy tests on prospective voters

More subtle approaches also were proposed, including longer residence periods, stricter naturalization laws, waiting periods before new citizens could vote, complex ballot laws, and elaborate systems of voter registration

Revising the rules

The laws governing elections in most states were revised often between the Civil War and World War I

Many of these laws were straightforwardly administrative, while other laws were more controversial, inspired by partisan interests, enacted to influence the outcome of elections.

Institutional reforms

The apportionment of state legislative as well as congressional seats was a key issue, generating recurrent conflicts, particularly between urban and rural areas.

Linked to apportionment was the location of district boundaries in states and within cities: gerrymandering was a routine form of political combat, practiced by both major parties against one another and against any upstart political organizations

Technical rules governing the presence of parties and candidates on the ballot also were subjects of contention—since they could encourage, or discourage, third parties and fusion slates

The electorate

* The most critical laws remained those that determined the size and contours of the electorate
* These were of two types.
 * First and most important were those that set out the fundamental qualifications that a man (or woman) had to meet in order to become an eligible voter
 * The second, of increasing significance, established the procedures that a potential voter had to follow in order to participate in elections

Economic qualifications

Contrary to received wisdom, economic requirements for voting were not a dead issue after 1850

Economic qualifications continued to offer opponents of universal suffrage a direct and potentially efficient means of winnowing out undesirable voters

The tax requirement had served as an obstacle to poor people’s voting and as a drain on the treasuries of both political parties

By the late 1880s, the Massachusetts Democratic Party—with more working-class supporters and thus greater financial exposure—reportedly was spending $50,000 at each election to pay the poll taxes of its supporters

Court on economic constraints

The U.S. Supreme Court made clear that it too did not see anything unconstitutional about taxpaying or property requirements in _Myers v. Anderson _ in 1915

The Court thus found the law to be racially discriminatory in violation of the Fifteenth Amendment; at the same time, however, it noted that economic discrimination in the form of a property requirement was presumed to be “free from constitutional objection.”

Class motivation

Overtly class-based economic restrictions were accompanied by legal changes expressly designed to reduce the number of “undesirable” immigrants who could vote

Beginning in the 1890s, the nation witnessed the growth of a significant movement to restrict immigration altogether, one source of which was widespread middle-class anxiety about the impact of the foreign-born on politics, particularly urban politics

As the ratio of immigrant workers to settlers soared and the need to encourage settlement diminished, granting the franchise to noncitizens seemed increasingly undesirable and risky.

Alien suffrage

* Most states rejected alien suffrage proposals in the late nineteenth century, and beginning with Idaho territory in 1874, states that had permitted noncitizens to vote began to repeal their declarant alien provisions
* This rollback picked up steam in the wake of the depression of the 1890s and the assassination of President McKinley by an immigrant in 1901;
 * it accelerated again during and after World War I, when concerns about the loyalty of the foreign-born contributed to a rare instance of wartime contraction of the franchise.
* The last state to permit noncitizens to vote was Arkansas, which abolished the practice in 1926

Alien suffrage

* Numerous states placed new obstacles in the path of immigrant voters
* Most were supported by some Republicans, opposed by Democrats, and justified on the grounds that they would reduce fraud
* Required naturalized citizens to present their naturalization papers to election officials before registering or voting
 * Although not unreasonable on its face, this requirement, as lawmakers knew, was a significant procedural hurdle for many immigrants, who might easily have lost their papers or been unaware of the requirement
 * Particularly when coupled with provisions that permitted anyone present at the polls to challenge the credentials of immigrant voters, these laws placed substantial discretionary power in the hands of local officials

Reducing immigrant voting

The concerns that prompted such efforts to keep immigrants from the polls also contributed to the tightening of federal immigration and naturalization laws between 1880 and the 1920s

Beginning in 1882, however, Congress began to narrow the channels through which the flow of European immigrants passed

Between 1906 and 1910, Congress also codified the naturalization laws, prohibiting many “undesirable” foreign-born residents from becoming citizens, setting a time limit on the validity of declarations of intent, and requiring candidates for naturalization to write their own names and present ample proof (including witnesses) of their eligibility and continuous residence in the United States for five years

These laws were unabashedly aimed at making it more difficult for men and women to become citizens, and by all accounts they succeeded, reducing the proportion of immigrants who could vote

Asian immigrants

Intense as apprehensions about poor European immigrants may have been, they paled in comparison to American attitudes toward the Chinese and other east Asians

By the final quarter of the nineteenth century, most Americans—and especially those on the West Coast—wanted not only to keep the Chinese from voting but to halt Chinese immigration and even deport those who were already here

Chinese exclusions

California Constitutional Convention of 1878–1879

“no native of China” (the wording was aimed at circumventing the Fifteenth Amendment’s ban on racial barriers) “shall ever exercise the privileges of an elector in this State.”

The suffrage provision of the 1879 constitution remained in force until 1926

Literacy tests

* Perhaps the most popular method of constricting the electorate was the literacy or education test
* Requiring voters to be literate, particularly in English, had a number of apparent virtues
 * it would reduce the “ignorance” of the electorate and weed out sizable numbers of poor immigrant voters (outside of the South, the native-born population was almost entirely literate)
 * It was more palatable than taxpaying restrictions or waiting periods for the foreign-born.
 * Literacy tests did not overtly discriminate against particular classes or ethnic groups, and illiteracy itself was a remediable shortcoming

Australian ballot

* An indirect and limited means of promoting a literate electorate was the adoption of the secret or Australian ballot.
* For much of the nineteenth century, voters had obtained their ballots from political parties
 * since the ballots generally contained only the names of an individual party’s candidates, literacy was not required
 * All that a man had to do was drop a ballot in a box
 * Since ballots tended to be of different sizes, shapes, and colors, a man’s vote was hardly a secret—to election officials, party bosses, employers, or anyone else watching the polls

Australian Ballot first appeared in Australia in 1856 and then was implemented in England in 1872

Australian ballot

The Australian ballot was an effort to remedy this situation and presumably the corruption and intimidation that flowed from it

It was a standard ballot, usually printed by the city or state, containing the names of all candidates for office

The voter, often in private, placed a mark by the names of the candidates or parties for whom he wished to vote

Australian ballot

The democratic virtues of secret voting were widely apparent

The Australian ballot was, however, an obstacle to participation by many illiterate foreign-born voters in the North, as well as uneducated Black voters in the South.

In some states, this problem was remedied by expressly permitting illiterate voters to be assisted or by attaching party emblems to the names of candidates

Few literacy tests in the North

The opposition was sufficiently strong that most states outside of the South declined to impose literacy tests

Northern Democrats, who counted the urban poor among their constituents, generally voted against education requirements

So too did politically organized ethnic groups, regardless of their party affiliation— which helps to explain why no English-language literacy tests were imposed in the Midwest: the German and Scandinavian communities of the Midwest, though often allied with the Republicans, vehemently opposed education requirements.

Increasing literacy tests in the North

* However, by the mid-1920s, thirteen states in the North and West were disfranchising illiterate citizens who met all other eligibility requirements
* In all of these states, the Republican Party was strong
 * several had large immigrant populations that played important roles in party competition
 * a handful of others were predominantly rural states with small but visible clusters of poor foreign-born voters
 * several also had significant Native-American populations

Literacy test effects

The potential impact of these literacy laws—all of which were sanctioned by the courts—was enormous.

According to the census (which relied on self-reporting), there were nearly five million illiterate men and women in the nation in 1920, roughly 8 percent of the voting-age population

Other sources suggest that in fact the figure was much higher. Twenty-five percent of men who took an army literacy test during World War I, for example, were judged to be illiterate and another 5 percent semiliterate

**A reasonable estimate is that a minimum of several hundred thousand voters—and likely more than a million—were barred by these tests, outside of the South**

Residency

The difficulty of defining residence, particularly in light of the increasingly accepted legal notion that sheer physical presence in a community for a specified length of time was not sufficient for a person to be considered a resident

Physical presence thus had to be accompanied by the intention of remaining in a community for what the courts came to describe as “an indefinite period”

Although the concept was reasonable, intention could be difficult to ascertain or prove

Courts found themselves evolving criteria to gauge the intentions of both individuals and groups (such as ministers and railway workers, who were often on the move) as they tried to apply broadly stated laws to extremely varied situations.

The insistence on intention tended to make legal residence harder to establish, especially for men whose occupations demanded mobility

Residency

No jurisdiction questioned the legitimacy of statutes or constitutional amendments establishing residence qualifications—even lengthy residence qualifications—for voting

In 1904, moreover, the U.S. Supreme Court, in _Pope v. Williams_ , affirmed the constitutionality of residency qualifications and state efforts to enforce them

In much of the nation, there was a broad consensus that a year’s residence in the state was necessary and sufficient for a man to responsibly exercise the franchise, although in many midwestern states the consensus period was six months

Absentee voting

The notion that legal residence was tied as much to intention as physical presence inexorably led states to consider mechanisms for absentee voting—for men and women who were temporarily away from home but intended to return

The Civil War—and the desire to permit soldiers to vote during the war—severed the link between voting and physical presence in a community

World War I added a new urgency to the issue, since nearly three million men were inducted into the army

By 1918, nearly all states had made provisions for men serving in the military to cast their ballots, at least in time of war

Absentee voting

By the end of World War I, more than twenty states had provided for absentee voting on the part of anyone who could demonstrate a work-related reason (and in a few cases, any reason) for being absent on election day.

Concerns about fraud generally were alleviated by tight procedural rules and requirements that absentee ballots be identical to conventional ones

A conservative estimate would be that 5–10 percent of the nation’s adult population failed to meet the residency requirements at each election

high enough to have potentially changed the outcomes of innumerable elections

Keeping Track of Voters

Before the 1870s in most states, there were no official preprepared lists of eligible voters, and men who sought to vote were not obliged to take any steps to establish their eligibility prior to election day

Between the 1870s and World War I, however, the majority of states adopted formal registration procedures, particularly for their larger cities

The rationale for requiring voters to register and have their eligibility certified in advance of elections was straightforward: it would help to eliminate fraud and also bring an end to disruptive election-day conflicts at the polls

Rules for eligibility

How far in advance of elections did a man or woman have to register?

When would registration offices be open?

Did one register in the county, the district, the precinct?

What documents had to be presented and issued?

How often did one have to register?

**All such questions had to be decided, and since the answers inescapably had implications for the composition of the electorate, they were a frequent source of contention**

Sunset laws

The two parties also feuded over the hours that the polls would be open

When the Republicans were able to, they passed laws closing the polls at sunset on the grounds that illegal voting was most likely to occur after dark

The Democrats protested that “sunset laws” kept workers from voting, and when in power, they ex-tended the hours into the evening

Women’s Suffrage

Why woman should vote?

Women did not seem (to men) to be endangered by their inability to vote

Nowhere did the enfranchisement of women seem likely to vest Republicans or Democrats with any discernible partisan advantage

Legal structure

* In 1872, Virginia Minor sued a St. Louis registrar who prevented her from registering to vote. She Claimed:
 * They infringed on Virginia Minor’s right of free speech, which was protected by the First Amendment
 * they contravened the Fourteenth Amendment’s command that states not abridge the “privileges or immunities” of citizens of the United States.
* Voting, the Minors claimed, was one of those privileges.
* Although the argument was a coherent one, the justices of the Supreme Court unanimously disagreed.
* **Upholding a lower court decision, they ruled in 1875 that suffrage was not coextensive with citizenship and thus that states possessed the authority to decide which citizens could and could not vote **

The era of maturity

* Suffragists lived in an era when a righteous cause—the abolition of slavery— that had triumphed over ferocious, entrenched opposition
* They had witnessed not only the end of slavery but also an extraordinary transformation of popular views and laws regarding Black suffrage
 * within a decade, an idea supported only by those on the fringes of politics had acquired the backing of the Republican Party and then been embedded in the Constitution

No Federal Action

In 1882, both houses of Congress appointed select committees on women’s suffrage, each of which recommended passage of an amendment.

The amendment was finally brought to a vote on the Senate floor, where, to the great disappointment of suffragists seated in the galleries, it was decisively defeated in January 1887 by a margin of thirty-four to sixteen (with twenty-six abstentions), a far cry from the two-thirds positive vote required for passage

No southern senator voted in favor of the amendment, while twenty-two voted against it

**After 1893, no congressional committee reported it favorably until late in the Progressive era **

State action

Although the issue was debated in numerous constitutional conventions, and referenda were held in eleven states (eight of them west of the Mississippi) between 1870 and 1910, concrete gains were few

The territory of Wyoming enfranchised women in 1869, a policy affirmed at statehood in 1889; Utah did the same in 1870 and 1896 (interrupted by a brief period when the federal government stripped Utah’s women of the suffrage as a curious step in its effort to rid the territory of polygamy); and Idaho and Colorado granted suffrage to women in the mid-1890s

Partial enfranchisement

A significant number of locales—states, counties, and municipalities—where partial suffrage was adopted, permitting women to vote in municipal elections, on liquor licensing matters, or for local school boards and on issues affecting education

The most common form of partial enfranchisement involved schools: legislatures, recognizing women’s responsibility for childrearing, as well as their education experience, responded to pressure from the suffrage movement by permitting women to vote on matters affecting schooling

Nearly all state legislatures considered adopting laws of this type, and by 1890, more than twenty states had done so

Challenges for the Suffragists

Many women themselves were either opposed, or relatively indifferent, to their own enfranchisement.

The demand for suffrage was most resonant among middle-class women, women from families engaged in the professions, trade or commerce, and educated women who lived in cities and developing towns

These were the women whose experiences and desires clashed most directly with traditional norms and who were most likely to seek the independence, autonomy, and equality that enfranchisement represented

Farm women, living in greater isolation and in more traditional social structures, were less responsive to calls for suffrage as well as more difficult to mobilize into collective action

Additional challenges

The political pressure that suffragists could exert thus was limited by their numbers, too limited to overcome the entrenched ideological and psychological resistance of many male voters and politicians.

The campaigns for suffrage generated organized opposition from some interest groups

Machine politicians also were dubious about women’s suffrage—in part for cultural reasons and in part because they always sought to keep the electorate as manageable as possible

Conservative members of the economic elite who took seriously the proposition that women would promote egalitarian social reforms

Win some, lose some

* The South was particularly resistant to enfranchising women
* But, the West was unusually receptive.
 * All of the states that fully enfranchised women in the nineteenth century were west of the Mississippi, as were most states that held referenda on the issue

Western suffrage

* What seems to have tipped the balance in a handful of western states (as well, perhaps, as in western states that dominated the first twentieth-century wave of suffrage victories) was a combination of several additional ingredients.
 * a more fluid pattern of party competition
 * included a highly visible number of working-class transients who labored in mining, railroading, and agriculture.
 * Since this group consisted overwhelmingly of single males, the enfranchisement of women offered discernible political benefits to the settler population at the expense of workers in extractive industries

Western suffrage

Most western states between 1850 and the 1890s did not experience the massive growth of an industrial working class that triggered such an antidemocratic reaction in the East and Midwest

The region’s swing against democracy was more mild and emotionally focused on the largely male Chinese population

_Doldrums and Democracy_

* In October 1893, the _New York Times _ declared in an editorial that “the cause of woman suffrage does not seem to have made the least progress in this part of the country in the last quarter of a century, if indeed it has not lost ground.”
 * Only a tiny portion of the nation’s women was fully enfranchised
 * interest was flagging in many states
 * most of the women who were entitled to vote in school board elections did not show up at the polls

Organization

National American Woman Suffrage Association (NAWSA) – combination of two organizations in 1890

By the end of the 1890s, NAWSA had created branches in every state, founded hundreds of local clubs, generated large quantities of literature, and was pressuring politicians everywhere

NAWSA also began to target and raise funds from wealthy, upper-class women, some of whom for the first time were lending their support to the movement

Shifts in ideology

* Shifts in ideology—or at least by shifts in the emphases placed on various arguments
 * Mirroring the broader middle-and upper-class disenchantment with democracy, suffragists placed less weight on equal rights arguments, which implied that everyone, male and female, should possess the right to vote
 * They stressed instead the more palatable essentialist theme that feminine qualities would be a welcome addition to the polity

Essentialist theme

Essentialist emphasis was reinforced by the increasingly common claim that women had distinct economic and social interests that could only be protected by possession of the right to vote.

White middle-class suffragists placed new weight on the argument that the enfranchisement of women would compensate for and counterbalance the votes of the ignorant and undesirable

Changing strategies

In the South, of course, the American Republic was thought to be threatened not by immigrants but by Blacks

It was argued that “the medium through which to retain the supremacy of the white race over the African”

In both the North and South, the notion that women were the antidote to undesirable voters led many suffragists, including Stanton, to join the conservative chorus calling for literacy tests as a means of shaping the electorate

**Suffragists effectively abandoned the principle of universal suffrage in favor of increasingly popular class-based limitations on electoral participation **

“the doldrums”

The period from 1896 to 1910 came to be known among suffragists as “the doldrums”

Although the issue was raised repeatedly in state legislatures and constitutional conventions, there were no new additions to the suffrage column.

In the South, the statistical argument was simply no match for the frenzied political circus that was disfranchising Blacks and poor whites in one state after another

In the North, the parallel push for suffrage for educated women collided head-on with the powerful middle-and upper-class desire to shrink the electorate

Internal contradictions

Whatever its statistical validity, the anti-Black, anti-immigrant, and anti–working class argument in favor of women’s suffrage was inescapably weakened by its own _internal contradictions _

An **antidemocratic** argument in favor of enlarging the franchise could neither overwhelm nor outflank the simpler, more consistent conservative view that the polity should be as _narrowly circumscribed_ as possible

Coalition building

The first decade of the twentieth century proved to be less a period of failure than of fruitful stock-taking and coalition building

The movement became socially and ideologically more diverse, attracting both elite and working-class supporters to complement its middle-class base

Female workers

By 1900, roughly one fifth of the labor force was female, and many of these women held poorly paid, semiskilled jobs; in 1905, there were 50,000 women in New York’s garment industry alone

New emphasis on working women had both ideological and pragmatic attractions for suffragists.

Female workers were described as “exemplars of independent womanhood”

They were also vulnerable and exploited victims of industrial capitalism whose plight readily tapped the broad impulses of Progressive-era social reform

Class and gender

That suffrage would never be achieved until it had gained the electoral support of working-class men—which meant emphasizing class as well as gender issues

Working women themselves, as well as their activist leaders, displayed new interest in acquiring the right to vote

This arose in part because of their difficulty unionizing and winning workplace conflicts

**They were convinced that state intervention could ameliorate their working conditions and that such intervention would be forthcoming only if they were enfranchised**

State-level Victories

Thanks in part to this convergence of working-class interest in suffrage with the suffragists’ interest in the working class, the campaign for women’s suffrage became a mass movement for the first time in its history after 1910

The movement also began to win some new victories. Washington permitted women to vote in 1910, followed by California in 1911, and Arizona, Kansas, and Oregon the following year; Illinois, in 1913, decided to allow women to vote in presidential elections and for all state and local offices not provided for in its constitution; and the next year, Montana and Nevada adopted full suffrage.

In 1912, Congress expressly authorized the territory of Alaska to enfranchise women if its legislature so chose

New allies

In 1910, President William H. Taft agreed to address the annual convention of NAWSA

That same year, a petition favoring a federal amendment, signed by more than 400,000 women, was presented to Congress

In 1912, the Progressive Party endorsed women’s right to vote, and in March 1913, Woodrow Wilson’s inauguration was partially eclipsed by a suffrage parade of 5,000 women in Washington

The following year, a Senate committee reported favorably on a federal amendment, and for the first time in decades a draft amendment was brought to the floor of Congress for a vote

But, opposition remained strong, particularly in the eastern half of the country.

Southern resistance

By the latter years of the Progressive era, African Americans had been successfully disfranchised throughout the South, and most whites were intent on keeping it that way

Politicians were loath to tinker at all with electoral laws, and they feared that _Black women might prove to be more difficult to keep from the polls than Black men_ —because Black women were believed to be more literate than men and _more aggressive about asserting their rights_ , and also because women would be unseemly targets of repressive violence

Many Southerners were convinced that a federal amendment would open the doors to **Washington’s intervention in elections, to enforcement—so glaringly absent—of the Fifteenth Amendment ** and any subsequent amendment that might appear to _guarantee the voting rights of Black women _

The Nineteenth Amendment

President Woodrow Wilson declined to endorse women’s suffrage, evasively reiterating his view that suffrage was a state issue

The national Democratic Party was similarly unresponsive

The Republican platform of 1916, in contrast, endorsed the cause, albeit in watered-down language

1916 election

* The 1916 elections set in motion two distinctive partisan dynamics that had surfaced periodically in suffrage struggles since the 1840s
 * the first resulted from the partial enfranchisement of women: **some women already could vote in all elections, and many could vote in some elections**
  * such circumstances gave women leverage to reward or punish politicians because of their (or their party’s) stance on the Nineteenth Amendment
 * The second dynamic was that of the “endgame,” the dynamic of possible or impending victory: **once it seemed likely or even possible that women’s suffrage eventually would be achieved** , either nationally or in an individual state, **the potential political cost of a vote against enfranchisement rose dramatically**

World War I

In 1917, the United States entered World War I

The most critical impact of the war was the opportunity it gave suffragists to contribute to the mobilization

The age-old argument that women should not vote because they did not bear arms was no longer applicable

“essential to the successful prosecution of the great war of humanity in which are engaged. . . . We have made partners of the women in this war. Shall we admit them only to a partnership of sacrifice and suffering and toll and not to a partnership of privilege and of right? This war could not have been fought . . . if it had not been for the services of women.”

Woodrow Wilson

Federal success

The suffragists’ able handling of the war crisis, coupled with continuing political pressure on Congress and the president, was rewarded in January 1918

The president, in an extraordinary address, announced his support of a federal suffrage amendment “as a war measure”

The next day, the House of Representatives voted in favor of the Nineteenth Amendment: the victory was won by one vote, with the Democrats splitting almost evenly while more than 80 percent of Republicans voted favorably.

Convincing the Senate

The Senate, where antisuffragist southern Democrats constituted a proportionally larger bloc, took an additional year and a half to endorse the amendment

After months of relentless political pressure and careful targeting of Republican and Democratic holdouts, the Senate—by a large Republican majority and a small Democratic one— finally came on board in the summer of 1919

State Ratification

Ratification depended on winning virtually every state outside of the South and the border states

Antisuffragists geared up for battle, denouncing the Nineteenth Amendment as a violation of states’ rights and a giant step toward socialism and free love

To no one’s surprise, the South remained recalcitrant

**On August 18, 1920, Tennessee, by a margin of one vote, became the thirty-sixth state to vote positively on the amendment; a week later, after ratification had been formally certified, the Nineteenth Amendment was law **

The Nineteenth Amendment

The Nineteenth Amendment

Section 1: **The right of citizens of the United States to vote shall not be denied or abridged by the United States or by any State on account of sex**

Section 2: **Congress shall have power to enforce this article by appropriate legislation**

After ratification

It is a well-known irony in American history that politics did not change very dramatically after women were enfranchised

The electorate nearly doubled in size between 1910 and 1920, but voting patterns and partisan alignments were little affected

**Women, moreover, did not rush out to vote in huge numbers: electoral turnout was even lower among women than among men **

How things changed

Political life in the 1920s was not nearly as vibrant or energetic as it had been in the 1890s or the latter years of the Progressive era; despite the identification of women with social reform, reforms were few during the first decade that women could vote

New issues, particularly those affecting women and children, were injected into the political arena, even if concrete reforms were slow to materialize

The social welfare programs of the 1930s were colored by the concerns of the female electorate and often promoted by women who had cut their political and organizational teeth in the suffrage movement

Franklin Roosevelt’s appointment of Frances Perkins as secretary of labor (and as the first woman to hold a cabinet position) would not have happened without the Nineteenth Amendment

Southern power

The suffragists’ prediction that the enfranchisement of women would not jeopardize white supremacy in the South proved to be on the mark

Although some (but not many) Black women were able to register to vote, the Democratic Party remained firmly in power, segregation and Black disfranchisement persisted, and the federal government steered clear of voting rights issues for another four decades

**Sex, thus, did not prove to be a significant dividing line in the American electorate** : some gender gaps in voting did occur in the early years (as well as more recently), but they were not large, and few issues sharply divided men and women.

How life changed

Women certainly were empowered by enfranchisement, and their lives consequently (if gradually) may have changed in a host of different ways, but they tended to vote for the same parties and candidates that their husbands, fathers, and brothers supported

Class, race, ethnicity, and religion remained the more salient predictors of a person’s voting behavior

Why was there opposition

The very absence of dramatic change after 1920 inescapably leaves one wondering what the adamant resistance was all about

Why, given the rather placid outcome, did so many men oppose women’s suffrage for so long?

Why did it take women seventy years after Seneca Falls to become enfranchised?

