---
title: "Who’s got talent?"
author: "Prof. Jonathan Cervas"
affiliation: Carnegie Mellon University
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    theme: yeti
    highlight: textmate
  pdf_document:
    citation_package: natbib
    keep_tex: false
    fig_caption: true
    latex_engine: pdflatex
  tufte::tufte_handout: default
bibliography: /Users/cervas/Downloads/library.bib
biblio-style: apsr
geometry: margin=1in
# fontfamily: libertine
fontsize: 11pt
# spacing: double
endnote: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Writing Lyrics to a Song or Poem about Voting Rights

## Objective: 
To understand the importance of voting rights and to express this through the creation of a song lyric or poem.

## Instructions:

1. Form a group of 2 or 3 students.
2. Consider the history of voting rights you've learned in class or recent developments in voting rights legislation.
3. Write a song lyric that includes:

  * A chorus
  * At least one refrain (which should be equivalent to a paragraph or so)

Or write a poem containing at least 5 sentences expressing:

  * The importance of voting rights 
  * The ongoing struggles to protect and expand these rights
  
4. Incorporate themes such as empowerment, equality, and justice into your lyric or poem.
5. Focus on your unique perspectives or experiences.
6. Use rhyming structures, metaphors, and other literary devices to make your song or poem engaging and memorable.

## Evaluation Criteria:
- Accuracy of historical information and understanding of voting rights
- Creativity and originality of lyrics or poem
- Use of literary devices to engage the listener or reader
- Originality
- Effective expression of the importance of voting rights

## Extra Credit:
- Performance of the song or poem in front of the class (or recorded and submitted for review). 
  * This will require you to bring your lyrics or poem to life by setting them to music or presenting them as a spoken word piece.
- You can do this during Tuesday's class (Feb 7, 2023). 
  * If one member of the group performs, each member gets 1 percentage point increase on their overall grade. 
  * If all members participate, each member gets 2 percentage points increase.

###### Note: Your song does not need to be fully produced, but it must include a chorus and at least one refrain. The focus of this assignment is on the lyrics.

## Directions:
- In Canvas, submit your song or poem lyrics into the text entry as part of the Assignment 2 submission portal. 
- If you choose to do the extra credit, a separate portal will be available to submit your composition.
- Words to your song or poem are due by Friday, February 10th at 11:59p. 
- You can submit this in the assignment "In-class exercise - Assignment 2".

